// The in-app help modal: a six-screen guided tour of the tool, reachable via
// the "?" button and auto-shown once on a true first-ever visit. Fully
// self-contained — queries its own DOM elements and wires its own listeners.
// Exports only the small surface app.js needs for its shared Escape/arrow-key
// coordination across all three overlays (help, AI reference, transfer picker).
import { hasSeenHelp, markHelpSeen } from './storage.js';

function icon(name) {
  return `<span class="icon icon-${name} help-icon"></span>`;
}

function chip(glyph) {
  return `<span class="help-chip">${glyph}</span>`;
}

function item(glyph, label, description) {
  return `<li>${chip(glyph)}<span><strong>${label}</strong> — ${description}</span></li>`;
}

const SCREENS = [
  {
    emoji: '👋',
    title: 'Welcome',
    body: `
      <div class="help-callout">
        <span class="help-callout-icon">🔒</span>
        <span><strong>Runs 100% locally.</strong> pptx-forge executes entirely in your browser. Your scripts, slide content, and workspace data are never transmitted anywhere — this tool makes no network requests of any kind.</span>
      </div>
      <div class="help-callout">
        <span class="help-callout-icon">🤖</span>
        <span><strong>Built to be used with an AI chatbot.</strong> Slides are meant to be generated by pasting the ✨ AI reference bundle into an external chat (ChatGPT, Claude, etc.) and pasting its generated code back in — not hand-written from scratch. See the AI Tooling screen for the full workflow.</span>
      </div>
      <p>pptx-forge builds PowerPoint decks from plain JavaScript. A <strong>workspace</strong> is a <code>theme.js</code> file plus one or more slide files — together they compile into a downloadable <code>.pptx</code>, right here in the browser.</p>
    `,
  },
  {
    emoji: '🗂️',
    title: 'Workspaces',
    body: `
      <p>The workspace switcher in the topbar lets you keep multiple decks-in-progress side by side. One workspace = one deck.</p>
      <ul class="help-list">
        ${item(icon('plus'), 'New', 'create a blank workspace.')}
        ${item('✎', 'Rename', 'click the pencil next to the switcher.')}
        ${item(icon('arrow-down-tray'), 'Import', 'load a workspace from a <code>.zip</code>.')}
        ${item(icon('arrow-up-tray'), 'Export', 'save the current workspace as a <code>.zip</code>.')}
        ${item(icon('trash'), 'Delete', 'remove the current workspace (cannot be undone).')}
      </ul>
    `,
  },
  {
    emoji: '📝',
    title: 'Slides & Editor',
    body: `
      <p>The sidebar lists <code>theme.js</code> at the top and your slide files below it. Click any file to open it in the editor — changes save automatically as you type.</p>
      <ul class="help-list">
        ${item(icon('plus'), 'New slide', 'adds a blank slide file.')}
        ${item(icon('arrow-down-tray'), 'Load slides', 'pick <code>.js</code> files from disk.')}
        ${item('✎', 'Rename', 'rename the active file.')}
        ${item(icon('trash'), 'Discard', `remove a slide, or ${icon('rotate-ccw')} <strong>Reset</strong> resets <code>theme.js</code> to its default.`)}
      </ul>
    `,
  },
  {
    emoji: '📦',
    title: 'Import/Export',
    body: `
      <p>Drag and drop <code>.js</code> files or a workspace <code>.zip</code> anywhere on the page, or use the sidebar's <strong>Load files</strong> button to pick them manually.</p>
      <p>A workspace <code>.zip</code> is laid out with <code>theme.js</code> at the root and slide files inside a <code>slides/</code> folder — that's what <strong>Export</strong> produces and <strong>Import</strong> expects.</p>
      <ul class="help-list">
        ${item(icon('scissors'), 'Move', 'send a slide to another workspace.')}
        ${item(icon('copy'), 'Copy', 'duplicate a slide into another workspace.')}
      </ul>
    `,
  },
  {
    emoji: '✨',
    title: 'AI Tooling',
    body: `
      <p>The <strong>✨ AI</strong> button copies a reference bundle — instructions and the component/theme API — to your clipboard, ready to paste into an external AI chat (ChatGPT, Claude, etc.).</p>
      <p>There's no live or embedded connection: you paste the bundle in, and paste the AI's generated slide code back into the editor yourself.</p>
      <div class="help-callout">
        <span class="help-callout-icon">🧩</span>
        <span>The <strong>Include builtin components</strong> toggle adds the pre-built comp/layout/frame component catalog to the copied bundle, for AI-generated slides that use those helpers.</span>
      </div>
    `,
  },
  {
    emoji: '⚡',
    title: 'Forge & Download',
    body: `
      <p><strong>⚡ Forge</strong> compiles <code>theme.js</code> and every slide into a single <code>.pptx</code> and downloads it.</p>
      <ul class="help-list">
        ${item('⏱', 'Timestamp', 'toggle appends a timestamp to the output filename.')}
        ${item(icon('arrow-up-tray'), 'Download', "saves just the active file's raw <code>.js</code> source.")}
      </ul>
    `,
  },
];

const el = {
  btn: document.getElementById('help-btn'),
  overlay: document.getElementById('help-overlay'),
  closeBtn: document.getElementById('help-overlay-close'),
  emoji: document.getElementById('help-emoji'),
  title: document.getElementById('help-title'),
  body: document.getElementById('help-body'),
  prevBtn: document.getElementById('help-prev-btn'),
  nextBtn: document.getElementById('help-next-btn'),
  dots: document.getElementById('help-dots'),
};

let index = 0;

function renderScreen() {
  const screen = SCREENS[index];
  el.emoji.textContent = screen.emoji;
  el.title.textContent = screen.title;
  el.body.innerHTML = screen.body;
  el.prevBtn.disabled = index === 0;
  el.nextBtn.disabled = index === SCREENS.length - 1;
  el.dots.querySelectorAll('.help-dot').forEach((dot, i) => {
    dot.classList.toggle('active', i === index);
    dot.setAttribute('aria-current', i === index ? 'true' : 'false');
  });
}

function renderDots() {
  el.dots.innerHTML = '';
  SCREENS.forEach((screen, i) => {
    const dot = document.createElement('button');
    dot.type = 'button';
    dot.className = 'help-dot';
    dot.setAttribute('aria-label', `Go to screen ${i + 1}: ${screen.title}`);
    dot.addEventListener('click', () => goTo(i));
    el.dots.appendChild(dot);
  });
}

function goTo(i) {
  index = Math.max(0, Math.min(SCREENS.length - 1, i));
  renderScreen();
}

// Reopening always starts at screen 1 — each open is "start of the tour",
// not a resume of wherever the user last left off.
export function openHelp() {
  index = 0;
  renderScreen();
  el.overlay.classList.add('visible');
}

export function closeHelp() {
  el.overlay.classList.remove('visible');
}

export function isHelpOpen() {
  return el.overlay.classList.contains('visible');
}

export function nextHelpScreen() {
  goTo(index + 1);
}

export function prevHelpScreen() {
  goTo(index - 1);
}

// isFirstVisit must be computed by the caller before the default-workspace
// auto-create logic runs (see storage.js hasAnyWorkspaceData); this only
// decides whether to act on it, and records that the modal has been shown.
export function maybeAutoOpenHelp(isFirstVisit) {
  if (isFirstVisit && !hasSeenHelp()) {
    openHelp();
    markHelpSeen();
  }
}

renderDots();
el.btn.addEventListener('click', openHelp);
el.closeBtn.addEventListener('click', closeHelp);
el.overlay.addEventListener('click', (e) => {
  if (e.target === el.overlay) closeHelp();
});
el.prevBtn.addEventListener('click', prevHelpScreen);
el.nextBtn.addEventListener('click', nextHelpScreen);
